- name: "Launch database container"
  docker:
    name: db
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    env:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

- name: "Launch wordpress container"
  docker:
    name: wordpress
    image: wordpress:latest
    links:
      - db:mysql
    ports:
      - 80:80
    env:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
