---
elb_port: 80
elb_sg:
  - 'sg-296c574d'
app_sg:
  - 'sg-6f6c570b'
  - 'sg-086c576c'
ec2_type: 't2.micro'
private_subnet:
  - 'subnet-2746ee43'
  - 'subnet-1c72a46a'
public_subnet:
  - 'subnet-2272a454'
  - 'subnet-7146ee15'
scale_desire: 1
scale_max: 1
scale_min: 1
sshkey: 'duy-demo'
app_name: 'wordpress'
app_version: 'latest'
env: 'dev'
